import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import { Github, Linkedin, Twitter } from "lucide-react";
import Provider from "@/app/Provider";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col antialiased bg-background text-foreground`}
      >
        <Provider>
          <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
            <div className="container mx-auto flex h-16 items-center px-4">
              <nav className="container mx-auto flex w-full items-center justify-between">
                <div className="flex items-center space-x-4">
                  <Link href="/" className="font-bold">
                    Home
                  </Link>
                </div>
                <div className="flex items-center space-x-4">
                  <span>Made By M-Tijani</span>
                  <Link
                    href="https://github.com/M-Tijani"
                    target="new"
                    className="text-foreground/60 transition-colors hover:text-foreground"
                  >
                    <Github className="h-5 w-5" />
                    <span className="sr-only">GitHub</span>
                  </Link>
                  <Link
                    href="https://twitter.com/mtijani2274450"
                    target="new"
                    className="text-foreground/60 transition-colors hover:text-foreground"
                  >
                    <Twitter className="h-5 w-5" />
                    <span className="sr-only">Twitter</span>
                  </Link>
                  <Link
                    href="https://www.linkedin.com/in/mahditijani/"
                    target="new"
                    className="text-foreground/60 transition-colors hover:text-foreground"
                  >
                    <Linkedin className="h-5 w-5" />
                    <span className="sr-only">LinkedIn</span>
                  </Link>
                </div>
              </nav>
            </div>
          </header>
          <div>{children}</div>
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}
